### ISSUE TITLE
问个问题。

### ISSUE THREAD

**Issue by liuxizhen2009** [tomzbj/fpm_skills#1]
你写的这些fpm skill 在哪里运行？怎么运行?

**Comment by tomzbj** [comment]
用fpm调用呀...

Hao Zhang
86-10-82543700
1-335, Technical Institute of Physics and Chemistry
29  Zhongguancun East Road
Haidian District, Beijing, 100190, P. R. China

2017-05-10 1:01 GMT+08:00 liuxizhen2009 <notifications@github.com>:

**Comment by liuxizhen2009** [comment]
把画封装的skill放到fpm的./skill文件夹里面，然后在自定义封装里面，就可以调用了。
谢谢你的回复。
